errText: { color: '#c0392b', fontSize: 12, marginTop: 6 },
  eyeBtn: { position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', color: '#8a948d', cursor: 'pointer', padding: 4 },
  hintBox: { marginTop: 24, background: '#f3f7f5', border: '1px solid #dcebe3', borderRadius: 12, padding: '12px 14px', fontSize: 12, color: '#5a6b62', lineHeight: 1.8, textAlign: 'center' },
  textarea: { width: '100%', boxSizing: 'border-box', padding: '12px 14px', borderRadius: 12, border: '1.5px solid #e0e5e2', fontSize: 14.5, color: '#1f2d26', background: '#fbfcfb', resize: 'vertical', fontFamily: 'inherit', transition: 'border-color .15s, box-shadow .15s' },
  photoSlot: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', border: '1.5px dashed #cfe0d7', borderRadius: 14, padding: '22px 14px', cursor: 'pointer', background: '#fafcfb', transition: 'border-color .15s, background .15s' },
  photoPreviewWrap: { position: 'relative', width: '100%' },
  photoPreview: { width: '100%', height: 140, objectFit: 'cover', borderRadius: 14, border: '1.5px solid #e0e5e2' },
  photoRemove: { position: 'absolute', top: 8, left: 8, width: 26, height: 26, borderRadius: '50%', background: 'rgba(20,30,25,0.65)', color: '#fff', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  submitBtn: { width: '100%', marginTop: 26, background: '#1f4438', color: '#fff', border: 'none', borderRadius: 14, padding: '14px', fontSize: 15, fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, transition: 'transform .1s' },
  linkBtn: { width: '100%', marginTop: 12, background: 'transparent', border: 'none', color: '#2f6b57', fontSize: 13.5, fontWeight: 600, cursor: 'pointer', padding: '8px' },
  statsRow: { display: 'flex', gap: 10, marginTop: 18 },
  statBox: { flex: 1, background: '#f3f7f5', borderRadius: 14, padding: '14px 12px', textAlign: 'center', border: '1px solid #dcebe3' },
  statNum: { fontSize: 22, fontWeight: 800, color: '#173b2f' },
  statLabel: { fontSize: 11.5, color: '#5a6b62', marginTop: 4 },
  searchWrap: { marginTop: 16, display: 'flex', alignItems: 'center', gap: 8, background: '#f5f6f5', border: '1.5px solid #e0e5e2', borderRadius: 12, padding: '10px 14px' },
  searchInput: { border: 'none', outline: 'none', background: 'transparent', fontSize: 14, flex: 1, color: '#1f2d26' },
  emptyState: { textAlign: 'center', color: '#8a948d', fontSize: 13.5, padding: '50px 10px' },
  visitCard: { display: 'flex', gap: 12, alignItems: 'center', padding: 12, borderRadius: 14, border: '1.5px solid #e5e9e6', background: '#fff', cursor: 'default', transition: 'all .15s' },
  visitThumb: { width: 48, height: 48, borderRadius: 10, objectFit: 'cover', flexShrink: 0 },
  visitThumbPlaceholder: { width: 48, height: 48, borderRadius: 10, background: '#eef2ef', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20 },
  visitPharmacy: { fontSize: 14.5, fontWeight: 700, color: '#1f2d26' },
  visitMeta: { fontSize: 11.5, color: '#8a948d', marginTop: 2 },
  visitNotes: { fontSize: 12.5, color: '#5a6b62', marginTop: 4, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  sectionTitle: { fontSize: 13.5, fontWeight: 700, color: '#3a4a41', marginBottom: 4 },
  empRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 14px', border: '1.5px solid #e5e9e6', borderRadius: 12, background: '#fafcfb' },
  adminTag: { background: '#1f4438', color: '#8fd9bd', fontSize: 10, padding: '2px 7px', borderRadius: 6, marginRight: 8, fontWeight: 700 },
  trashBtn: { background: 'none', border: 'none', color: '#c0392b', cursor: 'pointer', padding: 6 },
};
